/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as RegisterMentorRouteImport } from './routes/register.mentor'
import { Route as RegisterMenteeRouteImport } from './routes/register.mentee'
import { Route as AppSessionsRouteImport } from './routes/app.sessions'
import { Route as AppRequestsRouteImport } from './routes/app.requests'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppMentorsRouteImport } from './routes/app.mentors'
import { Route as AppMenteesRouteImport } from './routes/app.mentees'
import { Route as AppMatchRouteImport } from './routes/app.match'
import { Route as AppMentorsIdRouteImport } from './routes/app.mentors.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const RegisterMentorRoute = RegisterMentorRouteImport.update({
  id: '/register/mentor',
  path: '/register/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterMenteeRoute = RegisterMenteeRouteImport.update({
  id: '/register/mentee',
  path: '/register/mentee',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMentorsRoute = AppMentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => AppRoute,
} as any)
const AppMenteesRoute = AppMenteesRouteImport.update({
  id: '/mentees',
  path: '/mentees',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchRoute = AppMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AppRoute,
} as any)
const AppMentorsIdRoute = AppMentorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMentorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/match': typeof AppMatchRoute
  '/app/mentees': typeof AppMenteesRoute
  '/app/mentors': typeof AppMentorsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/sessions': typeof AppSessionsRoute
  '/register/mentee': typeof RegisterMenteeRoute
  '/register/mentor': typeof RegisterMentorRoute
  '/app/': typeof AppIndexRoute
  '/app/mentors/$id': typeof AppMentorsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/match': typeof AppMatchRoute
  '/app/mentees': typeof AppMenteesRoute
  '/app/mentors': typeof AppMentorsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/sessions': typeof AppSessionsRoute
  '/register/mentee': typeof RegisterMenteeRoute
  '/register/mentor': typeof RegisterMentorRoute
  '/app': typeof AppIndexRoute
  '/app/mentors/$id': typeof AppMentorsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/match': typeof AppMatchRoute
  '/app/mentees': typeof AppMenteesRoute
  '/app/mentors': typeof AppMentorsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/sessions': typeof AppSessionsRoute
  '/register/mentee': typeof RegisterMenteeRoute
  '/register/mentor': typeof RegisterMentorRoute
  '/app/': typeof AppIndexRoute
  '/app/mentors/$id': typeof AppMentorsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/match'
    | '/app/mentees'
    | '/app/mentors'
    | '/app/profile'
    | '/app/requests'
    | '/app/sessions'
    | '/register/mentee'
    | '/register/mentor'
    | '/app/'
    | '/app/mentors/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/match'
    | '/app/mentees'
    | '/app/mentors'
    | '/app/profile'
    | '/app/requests'
    | '/app/sessions'
    | '/register/mentee'
    | '/register/mentor'
    | '/app'
    | '/app/mentors/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/match'
    | '/app/mentees'
    | '/app/mentors'
    | '/app/profile'
    | '/app/requests'
    | '/app/sessions'
    | '/register/mentee'
    | '/register/mentor'
    | '/app/'
    | '/app/mentors/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterMenteeRoute: typeof RegisterMenteeRoute
  RegisterMentorRoute: typeof RegisterMentorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/register/mentor': {
      id: '/register/mentor'
      path: '/register/mentor'
      fullPath: '/register/mentor'
      preLoaderRoute: typeof RegisterMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/mentee': {
      id: '/register/mentee'
      path: '/register/mentee'
      fullPath: '/register/mentee'
      preLoaderRoute: typeof RegisterMenteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sessions': {
      id: '/app/sessions'
      path: '/sessions'
      fullPath: '/app/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests': {
      id: '/app/requests'
      path: '/requests'
      fullPath: '/app/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mentors': {
      id: '/app/mentors'
      path: '/mentors'
      fullPath: '/app/mentors'
      preLoaderRoute: typeof AppMentorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mentees': {
      id: '/app/mentees'
      path: '/mentees'
      fullPath: '/app/mentees'
      preLoaderRoute: typeof AppMenteesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/match': {
      id: '/app/match'
      path: '/match'
      fullPath: '/app/match'
      preLoaderRoute: typeof AppMatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mentors/$id': {
      id: '/app/mentors/$id'
      path: '/$id'
      fullPath: '/app/mentors/$id'
      preLoaderRoute: typeof AppMentorsIdRouteImport
      parentRoute: typeof AppMentorsRoute
    }
  }
}

interface AppMentorsRouteChildren {
  AppMentorsIdRoute: typeof AppMentorsIdRoute
}

const AppMentorsRouteChildren: AppMentorsRouteChildren = {
  AppMentorsIdRoute: AppMentorsIdRoute,
}

const AppMentorsRouteWithChildren = AppMentorsRoute._addFileChildren(
  AppMentorsRouteChildren,
)

interface AppRouteChildren {
  AppMatchRoute: typeof AppMatchRoute
  AppMenteesRoute: typeof AppMenteesRoute
  AppMentorsRoute: typeof AppMentorsRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMatchRoute: AppMatchRoute,
  AppMenteesRoute: AppMenteesRoute,
  AppMentorsRoute: AppMentorsRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterMenteeRoute: RegisterMenteeRoute,
  RegisterMentorRoute: RegisterMentorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
